package skald_core

import "core:fmt"
import "core:strings"

// =================================================================================
// Provenance (roadmap packet B12 / A2).
//
// Every emitted file carries who generated it and a digest of what it was
// generated from. A game team that finds a generated_audio.odin checked in
// next to three .skald.json files can tell which one it came from, and whether
// the generator that made it is the one in their checkout. Before B12 the
// header said only "Generated by Skald." — F-C4-8/9: no stamp anywhere on the
// deliverable, so a stale export and a fresh one were indistinguishable.
//
// FNV-1a lives HERE, not in main.odin, because both halves need it: main
// digests its own embedded sources (the -version stamp, packet A2) and core
// digests the input JSON (this packet). One implementation; the TypeScript
// mirror in skald-ui/src/main/codegenStamp.ts recomputes the source digest
// from the files on disk and must match it byte for byte, which is why the
// constants are pinned by tests/unit/provenance_test.odin.
// =================================================================================

FNV1A64_OFFSET :: 0xcbf29ce484222325
FNV1A64_PRIME :: 0x100000001b3

/// FNV-1a, 64-bit, streamable via `seed`. Chosen because it is short enough to
/// be provably identical in Odin and in TypeScript and needs no crypto
/// dependency on either side. This is a drift detector, not a security
/// boundary — nothing here defends against a hostile file, only a stale one.
fnv1a64 :: proc(data: []byte, seed: u64 = FNV1A64_OFFSET) -> u64 {
	h := seed
	for b in data {
		h ~= u64(b)
		h *= FNV1A64_PRIME
	}
	return h
}

/// G5 (roadmap 9.18): the seed for an Instrument's pitch/velocity jitter RNG,
/// derived from its resolved export prefix rather than a literal baked at
/// generation time by hand. Reuses fnv1a64 rather than a second hash — "one
/// implementation, not two that can drift" is why FNV-1a lives here at all —
/// and folds the 64-bit digest into 32 bits with xor rather than a truncating
/// cast, so both halves of the digest affect the seed. Deterministic in the
/// input (same export prefix -> same seed -> same jitter sequence on every
/// generation), which is what makes a jittered golden reproducible at all.
jitter_seed_from_name :: proc(name: string) -> u32 {
	h := fnv1a64(transmute([]byte)name)
	return u32(h) ~ u32(h >> 32)
}

/// Digest of an input file with every CR byte skipped. Deliberately
/// line-ending-insensitive: with core.autocrlf the same committed .skald.json
/// is CRLF in a Windows working tree and LF in a `git archive` export or a
/// Linux runner, and a digest that saw the difference would make every golden
/// red in scripts/verify-baseline.ps1 while green in the tree — the exact
/// "whose fault is it" confusion TESTING.md exists to prevent. Identity of the
/// authored content is what the header promises, and CRs are not content.
input_digest :: proc(data: []byte) -> u64 {
	h := u64(FNV1A64_OFFSET)
	for b in data {
		if b == '\r' do continue
		h ~= u64(b)
		h *= FNV1A64_PRIME
	}
	return h
}

/// What the header prints. Both strings are opaque to core: main.odin decides
/// what `generator` says (its source digest, or the SKALD_CODEGEN_STAMP env
/// override the golden harnesses set so the snapshots do not churn on every
/// generator edit) and formats `input` from input_digest. Empty means the
/// caller had nothing to say, and the header says so rather than omitting the
/// line — a missing line is invisible, "unstamped" is a finding.
Provenance :: struct {
	generator: string,
	input:     string,
}

emit_provenance_banner :: proc(sb: ^strings.Builder, provenance: Provenance) {
	generator := provenance.generator
	if generator == "" do generator = "unstamped"
	input := provenance.input
	if input == "" do input = "unstamped"
	fmt.sbprint(sb, "// AUTO-GENERATED — DO NOT EDIT. Every hand edit here is lost on the next\n")
	fmt.sbprint(sb, "// Generate; change the .skald.json in the editor and regenerate instead.\n")
	fmt.sbprintf(sb, "//   generator: %s\n", generator)
	fmt.sbprintf(sb, "//   input:     %s\n", input)
}
