package generated_audio

// =====================================================================
// Generated by Skald.
//
// SFX assets: Asset
// Music Layer assets: (none)
//
// Game integration: import this package and use the per-asset APIs.
//   SFX:         <Foo>_init, <Foo>_trigger, <Foo>_process, <Foo>_is_playing
//   Music Layer: <Bar>_init, <Bar>_start, <Bar>_stop, <Bar>_process,
//                <Bar>_set_loop
//
// project_init/process/destroy is a convenience wrapper for the test
// harness only — game code should consume per-asset procs directly.
// =====================================================================

import "core:math"
import "core:math/rand"

PRNG_State :: struct {
	state: u32,
}

next_float32 :: proc(rng: ^PRNG_State) -> f32 {
	x := rng.state
	x ~= x << 13
	x ~= x >> 17
	x ~= x << 5
	if x == 0 do x = 0xDEADBEEF
	rng.state = x
	return f32(x) / 4294967296.0
}

ADSR_Stage :: enum { Idle, Attack, Decay, Sustain, Release }

skald_wavetable_shape :: proc(idx: int, ph: f32) -> f32 {
	switch idx {
	case 1: return abs(ph * 4.0 - 2.0) - 1.0
	case 2: return ph * 2.0 - 1.0
	case 3: return ph < 0.5 ? 1.0 : -1.0
	}
	return math.sin(ph * 2.0 * f32(math.PI))
}

skald_wavetable_sample :: proc(ph: f32, pos: f32) -> f32 {
	p := math.clamp(pos, 0.0, 3.0)
	i1 := int(p)
	i2 := (i1 + 1) % 4
	frac := p - f32(i1)
	s1 := skald_wavetable_shape(i1, ph)
	s2 := skald_wavetable_shape(i2, ph)
	return s1 + (s2 - s1) * frac
}

Note_Event :: struct {
	note: u8,
	velocity: f32,
	start_time: f32,
	step: int,
	duration: f32,
}

Skald_Param_Info :: struct {
	name:    string,
	min:     f32,
	max:     f32,
	default: f32,
	unit:    string,
}

Asset_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	wavetable_1_phase: f32,
	adsr_2_stage: ADSR_Stage,
	adsr_2_release_level: f32,
}

Asset_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [8]Asset_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	position: f32,
}

Asset_init :: proc(p: ^Asset_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 120.000000000
	p.prng.state = 12345
	p.loop = true
	p.position = 0.000000000
}

Asset_note_on :: proc(p: ^Asset_Processor, note: u8, velocity: f32, duration: f32) {
	voice_idx := -1
	for i in 0..<8 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_age: f32 = -1.0
		for i in 0..<8 {
			if p.voices[i].age > oldest_age {
				oldest_age = p.voices[i].age
				voice_idx = i
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.050000001
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.wavetable_1_phase = 0.0
	v.adsr_2_stage = .Attack
	v.adsr_2_release_level = 0.0
}

Asset_note_off :: proc(p: ^Asset_Processor, note: u8) {
	best := -1
	best_age: f32 = -1.0
	for i in 0..<8 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_2_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_2_stage = .Release
	}
}

Asset_trigger :: proc(p: ^Asset_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	Asset_note_on(p, note, velocity, duration)
}

Asset_start :: proc(p: ^Asset_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

Asset_stop :: proc(p: ^Asset_Processor) {
	p.playing = false
}

Asset_set_loop :: proc(p: ^Asset_Processor, loop: bool) {
	p.loop = loop
}

Asset_is_playing :: proc(p: ^Asset_Processor) -> bool {
	if p.playing do return true
	for i in 0..<8 {
		if p.voices[i].active do return true
	}
	return false
}

Asset_set_position :: proc(p: ^Asset_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 3.000000000 do v = 3.000000000
	p.position = v
}

Asset_PARAMS := []Skald_Param_Info{
	{"position", 0.000000000, 3.000000000, 0.000000000, ""},
}

Asset_set_param :: proc(p: ^Asset_Processor, name: string, value: f32) -> bool {
	switch name {
	case "position":
		Asset_set_position(p, value)
		return true
	}
	return false
}

Asset_get_param :: proc(p: ^Asset_Processor, name: string) -> (f32, bool) {
	switch name {
	case "position":
		return p.position, true
	}
	return 0.0, false
}

Asset_process :: proc(p: ^Asset_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	p.total_samples += 1

	for v_idx in 0..<8 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.current_freq != voice.target_freq {
			glide_k := 1.0 / math.max(voice.glide_time * sample_rate, 1.0)
			if glide_k > 1.0 do glide_k = 1.0
			voice.current_freq += (voice.target_freq - voice.current_freq) * glide_k
			if abs(voice.target_freq - voice.current_freq) < 0.1 do voice.current_freq = voice.target_freq
		}
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_2_stage != .Release && voice.adsr_2_stage != .Idle {
				voice.adsr_2_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_1_out: f32 = 0.0
		node_2_out: f32 = 0.0
		node_3_out: f32 = 0.0

		// --- Wavetable Node 1 ---
		voice.wavetable_1_phase = math.mod(voice.wavetable_1_phase + ((voice.current_freq) / sample_rate), 1.0);
		if voice.wavetable_1_phase < 0.0 do voice.wavetable_1_phase += 1.0;
		node_1_out = skald_wavetable_sample(voice.wavetable_1_phase, f32(p.position)) * (f32(1.000000000));

		// --- ADSR Node 2 ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_2_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (f32(0.010000000)) > 0 do envelope = voice.age / math.max(f32(f32(0.010000000)), 0.000001); else do envelope = 1.0;
				voice.adsr_2_release_level = envelope;
				if voice.age >= (f32(0.010000000)) {
					voice.adsr_2_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (f32(0.010000000));
				if (f32(0.050000000)) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(f32(0.050000000)), 0.000001)) * (1.0 - (f32(0.900000000))); else do envelope = (f32(0.900000000));
				voice.adsr_2_release_level = envelope;
				if time_in_decay >= (f32(0.050000000)) {
					voice.adsr_2_stage = .Sustain;
				}
			case .Sustain:
				envelope = (f32(0.900000000));
				voice.adsr_2_release_level = envelope;
				if envelope <= 0.0001 do voice.adsr_2_stage = .Idle;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (f32(0.200000000)) > 0 do envelope = voice.adsr_2_release_level * (1.0 - (time_in_release / math.max(f32(f32(0.200000000)), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_2_stage = .Idle;
				}
			}
			vel_scale_2: f32 = (1.0 - (f32(0.500000000))) + (f32(0.500000000)) * voice.velocity;
			node_2_out = ((node_1_out)) * envelope * (f32(1.000000000)) * vel_scale_2;
		}

		output_left += node_2_out
		output_right += node_2_out
		if voice.adsr_2_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}
	return output_left * f32(1.000000000), output_right * f32(1.000000000)
}
Asset_process_sequence :: proc(p: ^Asset_Processor) {
}

// --- Project Wrapper (test-harness convenience) ---
Project_State :: struct {
	Asset: ^Asset_Processor,
}

project_init :: proc(p: ^Project_State, sr: f32) {
	p.Asset = new(Asset_Processor)
	Asset_init(p.Asset, sr)
}

project_process :: proc(p: ^Project_State) -> (f32, f32) {
	mixed_left: f32 = 0.0
	mixed_right: f32 = 0.0
	{ l, r := Asset_process(p.Asset); mixed_left += l; mixed_right += r }
	mixed_left = math.tanh(mixed_left * 0.800000012)
	mixed_right = math.tanh(mixed_right * 0.800000012)
	return mixed_left, mixed_right
}

project_destroy :: proc(p: ^Project_State) {
	free(p.Asset)
}

