// =====================================================================
// Generated by Skald.
//
// SFX assets: Asset Asset_2
// Music Layer assets: (none)
//
// Game integration: import this package and use the per-asset APIs.
//   SFX:         <Foo>_init, <Foo>_trigger, <Foo>_process, <Foo>_is_playing
//   Music Layer: <Bar>_init, <Bar>_start, <Bar>_stop, <Bar>_process,
//                <Bar>_set_loop
//
// project_init/process/destroy is a convenience wrapper for the test
// harness only — game code should consume per-asset procs directly.
// =====================================================================

package dups_pkg

import "core:math"
import "core:math/rand"

PRNG_State :: struct {
	state: u32,
}

next_float32 :: proc(rng: ^PRNG_State) -> f32 {
	x := rng.state
	x ~= x << 13
	x ~= x >> 17
	x ~= x << 5
	if x == 0 do x = 0xDEADBEEF
	rng.state = x
	return f32(x) / 4294967296.0
}

ADSR_Stage :: enum { Idle, Attack, Decay, Sustain, Release }

Note_Event :: struct {
	note: u8,
	velocity: f32,
	start_time: f32,
	step: int,
	duration: f32,
}

Skald_Param_Info :: struct {
	name:    string,
	min:     f32,
	max:     f32,
	default: f32,
	unit:    string,
}

Asset_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	osc_1_phase: [1]f32,
}

Asset_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [1]Asset_Voice_State,
	next_voice_idx: int,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
}

Asset_init :: proc(p: ^Asset_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 120.000
	p.prng.state = 12345
	p.loop = true
}

Asset_note_on :: proc(p: ^Asset_Processor, note: u8, velocity: f32, duration: f32) {
	voice_idx := -1
	for i in 0..<1 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	if voice_idx == -1 {
		voice_idx = p.next_voice_idx
		p.next_voice_idx = (p.next_voice_idx + 1) % 1
	}

	v := &p.voices[voice_idx]
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.current_freq = freq
	v.glide_time = 0.050
	v.duration = duration
}

Asset_note_off :: proc(p: ^Asset_Processor, note: u8) {
	for i in 0..<1 {
		if p.voices[i].active && p.voices[i].note == note {
			releasing := false
			p.voices[i].time_released = p.voices[i].age
			if !releasing do p.voices[i].active = false
		}
	}
}

Asset_trigger :: proc(p: ^Asset_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	Asset_note_on(p, note, velocity, duration)
}

Asset_start :: proc(p: ^Asset_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
}

Asset_stop :: proc(p: ^Asset_Processor) {
	p.playing = false
}

Asset_set_loop :: proc(p: ^Asset_Processor, loop: bool) {
	p.loop = loop
}

Asset_is_playing :: proc(p: ^Asset_Processor) -> bool {
	if p.playing do return true
	for i in 0..<1 {
		if p.voices[i].active do return true
	}
	return false
}

Asset_PARAMS := []Skald_Param_Info{
}

Asset_set_param :: proc(p: ^Asset_Processor, name: string, value: f32) -> bool {
	return false
}

Asset_get_param :: proc(p: ^Asset_Processor, name: string) -> (f32, bool) {
	return 0.0, false
}

Asset_process :: proc(p: ^Asset_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	p.total_samples += 1

	for v_idx in 0..<1 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.age >= voice.duration && voice.duration > 0.0 {
		}
		voice_busy := false
		node_1_out: f32 = 0.0
		node_2_out: f32 = 0.0

		// --- Oscillator Node 1 (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 1;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (5.000);
				detuned_freq := (440.000) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads := f32(0.000) * (f32(math.PI) / 180.0);
				voice.osc_1_phase[i] = math.mod(voice.osc_1_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := voice.osc_1_phase[i] + phase_rads;
				switch "Sine" {
				case "Sawtooth":
					unison_out += ((final_phase / f32(math.PI)) - 1.0);
				case "Square":
					if math.sin(final_phase) > 0.500 do unison_out += 1.0; else do unison_out -= 1.0;
				case "Triangle":
					unison_out += (2.0 / f32(math.PI)) * math.asin(math.sin(final_phase));
				case:
					unison_out += math.sin(final_phase);
				}
			}
			if unison_count > 0 do node_1_out = (unison_out / f32(unison_count)) * (0.500);
		}

		output_left += node_1_out
		output_right += node_1_out
		if voice.duration > 0.0 && voice.age >= voice.duration do voice.active = false
	}
	return output_left, output_right
}
Asset_process_sequence :: proc(p: ^Asset_Processor) {
}

Asset_2_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	osc_3_phase: [1]f32,
}

Asset_2_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [1]Asset_2_Voice_State,
	next_voice_idx: int,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
}

Asset_2_init :: proc(p: ^Asset_2_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 120.000
	p.prng.state = 12345
	p.loop = true
}

Asset_2_note_on :: proc(p: ^Asset_2_Processor, note: u8, velocity: f32, duration: f32) {
	voice_idx := -1
	for i in 0..<1 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	if voice_idx == -1 {
		voice_idx = p.next_voice_idx
		p.next_voice_idx = (p.next_voice_idx + 1) % 1
	}

	v := &p.voices[voice_idx]
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.current_freq = freq
	v.glide_time = 0.050
	v.duration = duration
}

Asset_2_note_off :: proc(p: ^Asset_2_Processor, note: u8) {
	for i in 0..<1 {
		if p.voices[i].active && p.voices[i].note == note {
			releasing := false
			p.voices[i].time_released = p.voices[i].age
			if !releasing do p.voices[i].active = false
		}
	}
}

Asset_2_trigger :: proc(p: ^Asset_2_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	Asset_2_note_on(p, note, velocity, duration)
}

Asset_2_start :: proc(p: ^Asset_2_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
}

Asset_2_stop :: proc(p: ^Asset_2_Processor) {
	p.playing = false
}

Asset_2_set_loop :: proc(p: ^Asset_2_Processor, loop: bool) {
	p.loop = loop
}

Asset_2_is_playing :: proc(p: ^Asset_2_Processor) -> bool {
	if p.playing do return true
	for i in 0..<1 {
		if p.voices[i].active do return true
	}
	return false
}

Asset_2_PARAMS := []Skald_Param_Info{
}

Asset_2_set_param :: proc(p: ^Asset_2_Processor, name: string, value: f32) -> bool {
	return false
}

Asset_2_get_param :: proc(p: ^Asset_2_Processor, name: string) -> (f32, bool) {
	return 0.0, false
}

Asset_2_process :: proc(p: ^Asset_2_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	p.total_samples += 1

	for v_idx in 0..<1 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.age >= voice.duration && voice.duration > 0.0 {
		}
		voice_busy := false
		node_3_out: f32 = 0.0
		node_4_out: f32 = 0.0

		// --- Oscillator Node 3 (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 1;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (5.000);
				detuned_freq := (220.000) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads := f32(0.000) * (f32(math.PI) / 180.0);
				voice.osc_3_phase[i] = math.mod(voice.osc_3_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := voice.osc_3_phase[i] + phase_rads;
				switch "Sine" {
				case "Sawtooth":
					unison_out += ((final_phase / f32(math.PI)) - 1.0);
				case "Square":
					if math.sin(final_phase) > 0.500 do unison_out += 1.0; else do unison_out -= 1.0;
				case "Triangle":
					unison_out += (2.0 / f32(math.PI)) * math.asin(math.sin(final_phase));
				case:
					unison_out += math.sin(final_phase);
				}
			}
			if unison_count > 0 do node_3_out = (unison_out / f32(unison_count)) * (0.500);
		}

		output_left += node_3_out
		output_right += node_3_out
		if voice.duration > 0.0 && voice.age >= voice.duration do voice.active = false
	}
	return output_left, output_right
}
Asset_2_process_sequence :: proc(p: ^Asset_2_Processor) {
}

// --- Project Wrapper (test-harness convenience) ---
Project_State :: struct {
	Asset: ^Asset_Processor,
	Asset_2: ^Asset_2_Processor,
}

project_init :: proc(p: ^Project_State, sr: f32) {
	p.Asset = new(Asset_Processor)
	Asset_init(p.Asset, sr)
	p.Asset_2 = new(Asset_2_Processor)
	Asset_2_init(p.Asset_2, sr)
}

project_process :: proc(p: ^Project_State) -> (f32, f32) {
	mixed_left: f32 = 0.0
	mixed_right: f32 = 0.0
	{ l, r := Asset_process(p.Asset); mixed_left += l; mixed_right += r }
	{ l, r := Asset_2_process(p.Asset_2); mixed_left += l; mixed_right += r }
	mixed_left = math.tanh(mixed_left * 0.7) / 0.7
	mixed_right = math.tanh(mixed_right * 0.7) / 0.7
	return mixed_left, mixed_right
}

project_destroy :: proc(p: ^Project_State) {
	free(p.Asset)
	free(p.Asset_2)
}

