import { describe, it, expect, beforeEach } from 'vitest';
import { setupWebAudioMock } from '../webAudioMock';
import { createOscillatorNode } from '../../hooks/nodeEditor/audioNodeFactory/createOscillatorNode';
import { createDistortionNode } from '../../hooks/nodeEditor/audioNodeFactory/createDistortionNode';
import { createDelayNode } from '../../hooks/nodeEditor/audioNodeFactory/createDelayNode';
import { createReverbNode } from '../../hooks/nodeEditor/audioNodeFactory/createReverbNode';
import { connectNodes } from '../../hooks/nodeEditor/audioNodeUtils';

setupWebAudioMock();

describe('Combo: Effects Chain', () => {
    let context: AudioContext;

    beforeEach(() => {
        context = new AudioContext();
    });

    it('daisy chains connection: Osc -> Dist -> Delay -> Reverb -> Out', () => {
        const osc = createOscillatorNode(context, { id: 'osc', data: {} } as any);
        const dist = createDistortionNode(context, { id: 'dist', data: {} } as any);
        const delay = createDelayNode(context, { id: 'delay', data: {} } as any);
        const reverb = createReverbNode(context, { id: 'reverb', data: {} } as any);
        const output = context.createGain();

        // 1. Osc -> Distortion (Input)
        connectNodes(osc, dist, { id: 'e1', source: 'osc', target: 'dist' } as any);
        // Osc (Source) connects to Dist (Input)
        expect(osc.connect).toHaveBeenCalledWith(dist);

        // 2. Distortion -> Delay
        connectNodes(dist, delay, { id: 'e2', source: 'dist', target: 'delay' } as any);
        // Distortion OUTPUT (generated by factory, attached to input node) should connect to Delay INPUT
        const distOutput = (dist as any).output;
        expect(distOutput.connect).toHaveBeenCalledWith(delay);

        // 3. Delay -> Reverb
        connectNodes(delay, reverb, { id: 'e3', source: 'delay', target: 'reverb' } as any);
        const delayOutput = (delay as any).output;
        expect(delayOutput.connect).toHaveBeenCalledWith(reverb);

        // 4. Reverb -> Output
        connectNodes(reverb, output, { id: 'e4', source: 'reverb', target: 'out' } as any);
        const reverbOutput = (reverb as any).output;
        expect(reverbOutput.connect).toHaveBeenCalledWith(output);
    });
});
