package skald_unit_tests

// =====================================================================
// Roadmap packet G3 (§9.5) — runtime scale quantization.
//
// core.nearest_in_scale mirrors skald-ui/src/contexts/ScaleContext.tsx's
// nearestInScale case by case (see scale.odin's doc comment). These cases
// were generated by running the ACTUAL TS function (not re-derived by hand)
// against the same inputs — see the coordinator's compute_scale_cases.mjs —
// so a divergence here is the two implementations disagreeing, not an
// arithmetic mistake in the test.
//
// Run (from skald-backend\):
//   odin test tests\unit
// =====================================================================

import core "../../core"
import "core:testing"

@(test)
test_parse_scale_name_recognises_the_editor_spellings :: proc(t: ^testing.T) {
	testing.expect_value(t, core.parse_scale_name("Major"), core.Scale_Kind.Major)
	testing.expect_value(t, core.parse_scale_name("Minor"), core.Scale_Kind.Minor)
	testing.expect_value(t, core.parse_scale_name("Pentatonic"), core.Scale_Kind.Pentatonic)
	testing.expect_value(t, core.parse_scale_name("Dorian"), core.Scale_Kind.Dorian)
	testing.expect_value(t, core.parse_scale_name("Phrygian"), core.Scale_Kind.Phrygian)
	testing.expect_value(t, core.parse_scale_name("Lydian"), core.Scale_Kind.Lydian)
	testing.expect_value(t, core.parse_scale_name("Mixolydian"), core.Scale_Kind.Mixolydian)
	testing.expect_value(t, core.parse_scale_name("Chromatic"), core.Scale_Kind.Chromatic)
}

@(test)
test_parse_scale_name_defaults_to_chromatic :: proc(t: ^testing.T) {
	// Absent (every project before this packet), and anything unrecognised,
	// must resolve to the identity scale — quantizing to a scale nobody
	// authored would be worse than not quantizing at all.
	testing.expect_value(t, core.parse_scale_name(""), core.Scale_Kind.Chromatic)
	testing.expect_value(t, core.parse_scale_name("major"), core.Scale_Kind.Chromatic)
	testing.expect_value(t, core.parse_scale_name("Whole Tone"), core.Scale_Kind.Chromatic)
}

@(test)
test_parse_root_note_matches_editor_note_order :: proc(t: ^testing.T) {
	testing.expect_value(t, core.parse_root_note("C"), 0)
	testing.expect_value(t, core.parse_root_note("C#"), 1)
	testing.expect_value(t, core.parse_root_note("F#"), 6)
	testing.expect_value(t, core.parse_root_note("A#"), 10)
	testing.expect_value(t, core.parse_root_note("B"), 11)
	testing.expect_value(t, core.parse_root_note(""), 0)
	testing.expect_value(t, core.parse_root_note("H"), 0) // German spelling: unrecognised, not a crash
}

// (note, root name, root index, scale) -> expected, generated by running
// ScaleContext.tsx::nearestInScale itself against these exact inputs.
Nearest_Case :: struct {
	note:     int,
	root:     int,
	scale:    core.Scale_Kind,
	expected: int,
	why:      string,
}

NEAREST_CASES := []Nearest_Case{
	{60, 0, .Major, 60, "already in C Major (root C, 60=C)"},
	{61, 0, .Major, 60, "tie between C(0) and D(2): C listed first in SCALE_INTERVALS wins"},
	{63, 0, .Major, 62, "D#/Eb -> nearer D than E"},
	{66, 0, .Major, 65, "F# -> nearer F than G"},
	{70, 0, .Major, 69, "Bb -> nearer A than B"},
	{60, 2, .Major, 59, "root shifted to D: relative index 10 is nearest interval 9 (diff -1), not 11 (diff +1, tied on |diff| but interval 9 comes first)"},
	{61, 0, .Minor, 60, "C# in C Minor -> C"},
	{66, 0, .Minor, 65, "F# in C Minor -> F"},
	{61, 0, .Pentatonic, 60, "C# in C Pentatonic -> C"},
	{62, 0, .Pentatonic, 63, "D in C Pentatonic (no 2 in {0,3,5,7,10}) -> Eb"},
	{61, 0, .Dorian, 60, "C# in C Dorian -> C"},
	{61, 0, .Phrygian, 61, "C# IS in C Phrygian ({0,1,3,5,7,8,10}) -> unchanged"},
	{61, 0, .Lydian, 60, "C# in C Lydian -> C"},
	{61, 0, .Mixolydian, 60, "C# in C Mixolydian -> C"},
	{72, 0, .Major, 72, "octave-up C, already in scale"},
	{0, 0, .Major, 0, "note 0 edge"},
	{127, 0, .Major, 127, "note 127 edge: 127%12=7, 7 is in Major -> unchanged"},
	{61, 6, .Major, 61, "root F#: C# is relative 7, in Major -> unchanged"},
	{61, 10, .Minor, 61, "root A#: C# is relative 3, in Minor -> unchanged"},
	{65, 0, .Chromatic, 65, "Chromatic is the identity scale: every note is unchanged"},
}

@(test)
test_nearest_in_scale_matches_the_editor_pinned_cases :: proc(t: ^testing.T) {
	for c in NEAREST_CASES {
		got := core.nearest_in_scale(c.note, c.root, c.scale)
		testing.expectf(
			t, got == c.expected,
			"nearest_in_scale(note=%d, root=%d, scale=%v) = %d, want %d (%s)",
			c.note, c.root, c.scale, got, c.expected, c.why,
		)
	}
}

@(test)
test_raw_project_shape_reads_root_note_and_scale_name :: proc(t: ^testing.T) {
	src := `{
	  "project": {
	    "bpm": 120,
	    "root_note": "F#",
	    "scale_name": "Dorian",
	    "instruments": [
	      { "id": "a", "name": "Asset", "voice_count": 1,
	        "audio_graph": { "nodes": [
	          { "id": "out", "type": "GraphOutput", "parameters": {} }
	        ], "connections": [], "sequencer_tracks": [] } }
	    ]
	  }
	}`
	project, err := core.build_project_from_json(transmute([]byte)src)
	testing.expect(t, err == "", err)
	if err != "" do return
	testing.expect_value(t, project.root_note_index, 6)
	testing.expect_value(t, project.scale_kind, core.Scale_Kind.Dorian)
}

@(test)
test_raw_project_shape_defaults_scale_when_absent :: proc(t: ^testing.T) {
	// No root_note/scale_name at all — every project before this packet.
	src := `{
	  "project": {
	    "bpm": 120,
	    "instruments": [
	      { "id": "a", "name": "Asset", "voice_count": 1,
	        "audio_graph": { "nodes": [
	          { "id": "out", "type": "GraphOutput", "parameters": {} }
	        ], "connections": [], "sequencer_tracks": [] } }
	    ]
	  }
	}`
	project, err := core.build_project_from_json(transmute([]byte)src)
	testing.expect(t, err == "", err)
	if err != "" do return
	testing.expect_value(t, project.root_note_index, 0)
	testing.expect_value(t, project.scale_kind, core.Scale_Kind.Chromatic)
}

@(test)
test_graph_shape_reads_root_note_and_scale_name_from_the_session_block :: proc(t: ^testing.T) {
	src := `{
	  "version": 2,
	  "nodes": [
	    { "id": "inst1", "type": "instrument", "position": {"x":0,"y":0},
	      "data": { "name": "Bass Synth",
	                "subgraph": { "nodes": [
	                  { "id": "g", "type": "graphOutput", "position": {"x":0,"y":0}, "data": {} }
	                ], "connections": [] } } }
	  ],
	  "edges": [],
	  "sequencerTracks": [],
	  "session": { "bpm": 120, "rootNote": "A#", "scaleName": "Mixolydian" }
	}`
	project, err := core.build_project_from_json(transmute([]byte)src)
	testing.expect(t, err == "", err)
	if err != "" do return
	testing.expect_value(t, project.root_note_index, 10)
	testing.expect_value(t, project.scale_kind, core.Scale_Kind.Mixolydian)
}
