package generated_audio

// =====================================================================
// Generated by Skald.
// AUTO-GENERATED — DO NOT EDIT. Every hand edit here is lost on the next
// Generate; change the .skald.json in the editor and regenerate instead.
//   generator: skald_codegen fnv1a64:7aa7581032c48ab6
//   input:     fnv1a64:cac9916e7cd696e4
//
// SFX assets: Lead Kick_2 Bass
// Music Layer assets: Kick Kick_3 Lead_2
//
// Game integration: import this package and use the per-asset APIs.
//   SFX:         <Foo>_init, <Foo>_trigger, <Foo>_process, <Foo>_is_playing
//   Music Layer: <Bar>_init, <Bar>_start, <Bar>_stop, <Bar>_process,
//                <Bar>_set_loop
//
// <Foo>_trigger with duration<=0 (the default) plays a natural one-shot:
// the envelope holds through attack+decay, then releases (a patch with no
// envelope plays 1s). Pass an explicit duration in seconds to hold longer,
// or drive <Foo>_note_on / <Foo>_note_off yourself for full control.
//
// <Foo>_note_on clamps `note` to 0..127 and `velocity` to 0..1 SILENTLY —
// it is called at audio rate, so an out-of-range argument cannot afford a
// diagnostic. Check your own values if you need to know they were wrong.
// <Foo>_note_off clamps `note` the same way, because `note` is the key it
// matches voices on: if only one side clamped, note_off(200) would fail to
// release the voice note_on(200) parked at 127, and that voice would never
// free.
//
// THREADING: every call on one asset — _init, _note_on, _note_off, _trigger,
// _start, _stop, _set_*, _set_param, _process, _is_playing — must come from
// the thread that calls that asset's _process. The setters are plain field
// writes with no synchronization, so a setter from another thread while
// _process runs is a data race, not a late parameter change. Queue values
// across threads in your own code and apply them on the audio thread.
//
// Exposed parameters. Two setter styles per asset, both clamped to the range:
//   typed   <Foo>_set_<field>(p, value)
//   string  <Foo>_set_param(p, "<field>", value) -> bool   (false = unknown name;
//           also accepts the editor's "<nodeId>::<param>" key). <Foo>_get_param
//           reads back; <Foo>_PARAMS lists name/min/max/default/unit for UI binding.
// Stable identity: <Foo> is the Instrument's Export ID (its display name only when
//   no Export ID is set), so renaming the instrument does not rename its procs. A
//   typed setter's <field> gains a <Label>_ prefix when another node in the same asset
//   exposes the same parameter, and loses it when that exposure goes away. Game code
//   that must survive edits should key on <Foo>_set_param(p, "<nodeId>::<param>", v):
//   the node id never changes. Both halves are listed per setter below.
//   Kick: (no exposed parameters)
//   Lead: (no exposed parameters)
//   Kick_2: (no exposed parameters)
//   Bass
//     Bass_set_cutoff   min 20  max 20000  default 900  unit Hz   (node 2, param cutoff)
//   Kick_3: (no exposed parameters)
//   Lead_2: (no exposed parameters)
//
// project_init/process/destroy is a convenience wrapper for the test
// harness only — game code should consume per-asset procs directly.
// =====================================================================

import "core:math"
import "core:math/rand"

PRNG_State :: struct {
	state: u32,
}

next_float32 :: proc(rng: ^PRNG_State) -> f32 {
	x := rng.state
	x ~= x << 13
	x ~= x >> 17
	x ~= x << 5
	if x == 0 do x = 0xDEADBEEF
	rng.state = x
	return f32(x) / 4294967296.0
}

ADSR_Stage :: enum { Idle, Attack, Decay, Sustain, Release }

skald_wavetable_shape :: proc(idx: int, ph: f32, pw: f32) -> f32 {
	switch idx {
	case 1: return abs(ph * 4.0 - 2.0) - 1.0
	case 2: return ph * 2.0 - 1.0
	case 3: return ph < pw ? 1.0 : -1.0
	}
	return math.sin(ph * 2.0 * f32(math.PI))
}

skald_wavetable_sample :: proc(ph: f32, pos: f32, pw: f32) -> f32 {
	p := math.clamp(pos, 0.0, 3.0)
	i1 := int(p)
	i2 := (i1 + 1) % 4
	frac := p - f32(i1)
	s1 := skald_wavetable_shape(i1, ph, pw)
	s2 := skald_wavetable_shape(i2, ph, pw)
	return s1 + (s2 - s1) * frac
}

skald_master_flush_count: i32

// Soft limiter with a ceiling that really is 1.0 — plain tanh, not
// tanh(x*k)/k, which topped out above 1 and still clipped the device.
// Transparent for small signals (tanh(x) ~= x below ~0.3), saturating
// smoothly instead of clipping as the mix gets hot.
//
// E5: tanh(NaN) is NaN, and tanh(+-Inf) is +-1 — a NaN INPUT would poison
// the entire mix silently, and an Inf input would report a false full-scale
// tone. Flushed to silence and counted instead, here, so this is caught no
// matter which of the three call sites (a per-asset _process, project_process,
// or the wasm shim's skald_process) fed it a bad sample.
skald_soft_limit :: proc(l: f32, r: f32) -> (f32, f32) {
	lf, rf := l, r
	if math.is_nan(lf) || math.is_inf(lf) || math.is_nan(rf) || math.is_inf(rf) {
		lf, rf = 0.0, 0.0
		skald_master_flush_count += 1
	}
	return math.tanh(lf), math.tanh(rf)
}

// E5: one-pole DC blocker state, one instance per master bus (project_process
// or the wasm shim's skald_process — see skald_dc_block below). Reset
// alongside every other master-bus field (project_init / skald_init).
Skald_Dc_Block_State :: struct {
	x1_l, y1_l, x1_r, y1_r: f32,
}

// y = x - x1 + R*y1, R = 0.995 (~38 Hz cutoff at 48 kHz — see the note
// above generate_project_code's call to emit_dc_block_proc).
skald_dc_block :: proc(s: ^Skald_Dc_Block_State, l: f32, r: f32) -> (f32, f32) {
	yl := l - s.x1_l + 0.995 * s.y1_l
	yr := r - s.x1_r + 0.995 * s.y1_r
	s.x1_l, s.y1_l = l, yl
	s.x1_r, s.y1_r = r, yr
	return yl, yr
}

Note_Event :: struct {
	note: u8,
	velocity: f32,
	start_time: f32,
	step: int,
	duration: f32,
}

Skald_Param_Info :: struct {
	name:    string,
	min:     f32,
	max:     f32,
	default: f32,
	unit:    string,
}

Kick_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	osc_2_phase: [1]f32,
	adsr_3_stage: ADSR_Stage,
	adsr_3_release_level: f32,
	adsr_3_attack_start: f32,
}

Kick_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [1]Kick_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	volume: f32,
	nonfinite_count: i32,
}

Kick_init :: proc(p: ^Kick_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 120.000000000
	p.volume = 0.899999976
	p.prng.state = 12345
	p.loop = true
	p.voices = {}
	p.total_samples = 0
	p.playing = false
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
	p.ext_in_l = 0.0
	p.ext_in_r = 0.0
	p.nonfinite_count = 0
}

Kick_note_on :: proc(p: ^Kick_Processor, note: u8, velocity: f32, duration: f32) {
	// note and velocity are clamped silently to their MIDI/normalized domains.
	note := note
	if note > 127 do note = 127
	velocity := math.clamp(velocity, 0.0, 1.0)
	voice_idx := -1
	for i in 0..<1 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_releasing_age: f32 = -1.0
		for i in 0..<1 {
			releasing := true
			if p.voices[i].adsr_3_stage != .Release && p.voices[i].adsr_3_stage != .Idle do releasing = false
			if releasing && p.voices[i].age > oldest_releasing_age {
				oldest_releasing_age = p.voices[i].age
				voice_idx = i
			}
		}
		if voice_idx == -1 {
			oldest_age: f32 = -1.0
			for i in 0..<1 {
				if p.voices[i].age > oldest_age {
					oldest_age = p.voices[i].age
					voice_idx = i
				}
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	adsr_3_prev_level: f32 = 0.0
	if stolen && v.adsr_3_stage != .Idle {
		adsr_3_prev_level = v.adsr_3_release_level
		if v.adsr_3_stage == .Release {
			rel_t_3: f32 = (f32(0.050000000));
			if rel_t_3 > 0.0 {
				rf_3 := 1.0 - (v.age - v.time_released) / math.max(rel_t_3, 0.000001)
				if rf_3 < 0.0 do rf_3 = 0.0
				adsr_3_prev_level *= rf_3
			} else {
				adsr_3_prev_level = 0.0
			}
		}
	}
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.000000000
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.adsr_3_stage = .Attack
	v.adsr_3_attack_start = adsr_3_prev_level
	v.adsr_3_release_level = adsr_3_prev_level
	if !stolen {
		v.osc_2_phase = {}
	}
}

Kick_note_off :: proc(p: ^Kick_Processor, note: u8) {
	// Clamped to match _note_on: `note` is the voice key, so both must map it.
	note := note
	if note > 127 do note = 127
	best := -1
	best_age: f32 = -1.0
	for i in 0..<1 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_3_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_3_stage = .Release
	}
}

Kick_trigger :: proc(p: ^Kick_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (f32(0.001000000)) + (f32(0.090000000)) > d do d = (f32(0.001000000)) + (f32(0.090000000))
		if d <= 0.0 do d = 0.001
	}
	Kick_note_on(p, note, velocity, d)
}

Kick_feed_input :: proc(p: ^Kick_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

Kick_start :: proc(p: ^Kick_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

Kick_stop :: proc(p: ^Kick_Processor) {
	p.playing = false
}

Kick_set_loop :: proc(p: ^Kick_Processor, loop: bool) {
	p.loop = loop
}

Kick_set_volume :: proc(p: ^Kick_Processor, value: f32) {
	p.volume = math.clamp(value, 0.0, 1.0)
}

Kick_is_playing :: proc(p: ^Kick_Processor) -> bool {
	if p.playing do return true
	for i in 0..<1 {
		if p.voices[i].active do return true
	}
	return false
}

Kick_PARAMS := []Skald_Param_Info{
}

Kick_set_param :: proc(p: ^Kick_Processor, name: string, value: f32) -> bool {
	return false
}

Kick_get_param :: proc(p: ^Kick_Processor, name: string) -> (f32, bool) {
	return 0.0, false
}

Kick_process :: proc(p: ^Kick_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	Kick_process_sequence(p)
	p.total_samples += 1

	for v_idx in 0..<1 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_3_stage != .Release && voice.adsr_3_stage != .Idle {
				voice.adsr_3_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_1_out: f32 = 0.0
		node_2_out: f32 = 0.0
		node_3_out: f32 = 0.0
		node_4_out: f32 = 0.0

		// --- MIDI Input Node 1 ---
		node_1_out_pitch := (f32(voice.note) - 69.0) / 12.0
		node_1_out_gate := f32(1.0)
		if voice.time_released > 0.0 do node_1_out_gate = 0.0
		node_1_out_velocity := voice.velocity

		// --- Oscillator Node 2 (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 1;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (0.000000000);
				detuned_freq: f32 = ((voice.current_freq) * math.pow(2.0, math.clamp(f32(node_1_out_pitch), -10.0, 10.0))) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads: f32 = f32(f32(0.000000000)) * (f32(math.PI) / 180.0);
				voice.osc_2_phase[i] = math.mod(voice.osc_2_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := math.mod(voice.osc_2_phase[i] + phase_rads, 2 * f32(math.PI));
				unison_out += math.sin(final_phase);
			}
			node_2_out = (unison_out / f32(unison_count)) * (f32(0.800000000));
		}

		// --- ADSR Node 3 ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_3_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (f32(0.001000000)) > 0 do envelope = voice.adsr_3_attack_start + (1.0 - voice.adsr_3_attack_start) * (voice.age / math.max(f32(f32(0.001000000)), 0.000001)); else do envelope = 1.0;
				voice.adsr_3_release_level = envelope;
				if voice.age >= (f32(0.001000000)) {
					voice.adsr_3_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (f32(0.001000000));
				if (f32(0.090000000)) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(f32(0.090000000)), 0.000001)) * (1.0 - (f32(0.000000000))); else do envelope = (f32(0.000000000));
				voice.adsr_3_release_level = envelope;
				if time_in_decay >= (f32(0.090000000)) {
					voice.adsr_3_stage = .Sustain;
				}
			case .Sustain:
				envelope = (f32(0.000000000));
				voice.adsr_3_release_level = envelope;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (f32(0.050000000)) > 0 do envelope = voice.adsr_3_release_level * (1.0 - (time_in_release / math.max(f32(f32(0.050000000)), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_3_stage = .Idle;
				}
			}
			vel_scale_3: f32 = (1.0 - (f32(0.500000000))) + (f32(0.500000000)) * voice.velocity;
			node_3_out = ((node_1_out_gate + node_2_out)) * envelope * (f32(1.000000000)) * vel_scale_3;
		}

		output_left += node_3_out
		output_right += node_3_out
		if voice.adsr_3_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}
	if math.is_nan(output_left) || math.is_inf(output_left) || math.is_nan(output_right) || math.is_inf(output_right) {
		p.nonfinite_count += 1
		output_left, output_right = 0.0, 0.0
	}
	return skald_soft_limit(output_left * p.volume, output_right * p.volume)
}
Kick_process_sequence :: proc(p: ^Kick_Processor) {
	if !p.playing do return
	samples_per_step_f := p.sample_rate * 60.0 / (p.bpm * 4.0)
	if p.samples_until_next_step == 0 {
		// Track "Kick A" (16 steps)
		switch p.current_step % 16 {
		case 0:
			Kick_note_on(p, 36, 1.000000000, f32(0.100000001) * (60.0 / p.bpm / 4.0))
		case 4:
			Kick_note_on(p, 36, 1.000000000, f32(0.100000001) * (60.0 / p.bpm / 4.0))
		case 8:
			Kick_note_on(p, 36, 1.000000000, f32(0.100000001) * (60.0 / p.bpm / 4.0))
		case 12:
			Kick_note_on(p, 36, 1.000000000, f32(0.100000001) * (60.0 / p.bpm / 4.0))
		}
		p.current_step += 1
		if p.current_step >= 16 {
			if p.loop {
				p.current_step = 0
			} else {
				p.playing = false
			}
		}
		p.step_frac_acc += samples_per_step_f
		n_step := u64(math.max(p.step_frac_acc, 1.0))
		p.step_frac_acc -= f32(n_step)
		p.samples_until_next_step = n_step - 1
	} else {
		p.samples_until_next_step -= 1
	}
}

Lead_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	osc_2_phase: [2]f32,
	adsr_3_stage: ADSR_Stage,
	adsr_3_release_level: f32,
	adsr_3_attack_start: f32,
}

Lead_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [4]Lead_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	volume: f32,
	nonfinite_count: i32,
}

Lead_init :: proc(p: ^Lead_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 120.000000000
	p.volume = 0.750000000
	p.prng.state = 12345
	p.loop = true
	p.voices = {}
	p.total_samples = 0
	p.playing = false
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
	p.ext_in_l = 0.0
	p.ext_in_r = 0.0
	p.nonfinite_count = 0
}

Lead_note_on :: proc(p: ^Lead_Processor, note: u8, velocity: f32, duration: f32) {
	// note and velocity are clamped silently to their MIDI/normalized domains.
	note := note
	if note > 127 do note = 127
	velocity := math.clamp(velocity, 0.0, 1.0)
	voice_idx := -1
	for i in 0..<4 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_releasing_age: f32 = -1.0
		for i in 0..<4 {
			releasing := true
			if p.voices[i].adsr_3_stage != .Release && p.voices[i].adsr_3_stage != .Idle do releasing = false
			if releasing && p.voices[i].age > oldest_releasing_age {
				oldest_releasing_age = p.voices[i].age
				voice_idx = i
			}
		}
		if voice_idx == -1 {
			oldest_age: f32 = -1.0
			for i in 0..<4 {
				if p.voices[i].age > oldest_age {
					oldest_age = p.voices[i].age
					voice_idx = i
				}
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	adsr_3_prev_level: f32 = 0.0
	if stolen && v.adsr_3_stage != .Idle {
		adsr_3_prev_level = v.adsr_3_release_level
		if v.adsr_3_stage == .Release {
			rel_t_3: f32 = (f32(0.220000000));
			if rel_t_3 > 0.0 {
				rf_3 := 1.0 - (v.age - v.time_released) / math.max(rel_t_3, 0.000001)
				if rf_3 < 0.0 do rf_3 = 0.0
				adsr_3_prev_level *= rf_3
			} else {
				adsr_3_prev_level = 0.0
			}
		}
	}
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.010000000
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.adsr_3_stage = .Attack
	v.adsr_3_attack_start = adsr_3_prev_level
	v.adsr_3_release_level = adsr_3_prev_level
	if !stolen {
		v.osc_2_phase = {}
	}
}

Lead_note_off :: proc(p: ^Lead_Processor, note: u8) {
	// Clamped to match _note_on: `note` is the voice key, so both must map it.
	note := note
	if note > 127 do note = 127
	best := -1
	best_age: f32 = -1.0
	for i in 0..<4 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_3_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_3_stage = .Release
	}
}

Lead_trigger :: proc(p: ^Lead_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (f32(0.004000000)) + (f32(0.140000000)) > d do d = (f32(0.004000000)) + (f32(0.140000000))
		if d <= 0.0 do d = 0.001
	}
	Lead_note_on(p, note, velocity, d)
}

Lead_feed_input :: proc(p: ^Lead_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

Lead_start :: proc(p: ^Lead_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

Lead_stop :: proc(p: ^Lead_Processor) {
	p.playing = false
}

Lead_set_loop :: proc(p: ^Lead_Processor, loop: bool) {
	p.loop = loop
}

Lead_set_volume :: proc(p: ^Lead_Processor, value: f32) {
	p.volume = math.clamp(value, 0.0, 1.0)
}

Lead_is_playing :: proc(p: ^Lead_Processor) -> bool {
	if p.playing do return true
	for i in 0..<4 {
		if p.voices[i].active do return true
	}
	return false
}

Lead_PARAMS := []Skald_Param_Info{
}

Lead_set_param :: proc(p: ^Lead_Processor, name: string, value: f32) -> bool {
	return false
}

Lead_get_param :: proc(p: ^Lead_Processor, name: string) -> (f32, bool) {
	return 0.0, false
}

Lead_process :: proc(p: ^Lead_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	p.total_samples += 1

	for v_idx in 0..<4 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.current_freq != voice.target_freq {
			glide_k := 1.0 / math.max(voice.glide_time * sample_rate, 1.0)
			if glide_k > 1.0 do glide_k = 1.0
			voice.current_freq += (voice.target_freq - voice.current_freq) * glide_k
			if abs(voice.target_freq - voice.current_freq) < 0.1 do voice.current_freq = voice.target_freq
		}
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_3_stage != .Release && voice.adsr_3_stage != .Idle {
				voice.adsr_3_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_1_out: f32 = 0.0
		node_2_out: f32 = 0.0
		node_3_out: f32 = 0.0
		node_4_out: f32 = 0.0

		// --- MIDI Input Node 1 ---
		node_1_out_pitch := (f32(voice.note) - 69.0) / 12.0
		node_1_out_gate := f32(1.0)
		if voice.time_released > 0.0 do node_1_out_gate = 0.0
		node_1_out_velocity := voice.velocity

		// --- Oscillator Node 2 (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 2;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (6.000000000);
				detuned_freq: f32 = ((voice.current_freq) * math.pow(2.0, math.clamp(f32(node_1_out_pitch), -10.0, 10.0))) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads: f32 = f32(f32(0.000000000)) * (f32(math.PI) / 180.0);
				voice.osc_2_phase[i] = math.mod(voice.osc_2_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := math.mod(voice.osc_2_phase[i] + phase_rads, 2 * f32(math.PI));
				unison_out += ((final_phase / f32(math.PI)) - 1.0);
			}
			node_2_out = (unison_out / f32(unison_count)) * (f32(0.500000000));
		}

		// --- ADSR Node 3 ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_3_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (f32(0.004000000)) > 0 do envelope = voice.adsr_3_attack_start + (1.0 - voice.adsr_3_attack_start) * (voice.age / math.max(f32(f32(0.004000000)), 0.000001)); else do envelope = 1.0;
				voice.adsr_3_release_level = envelope;
				if voice.age >= (f32(0.004000000)) {
					voice.adsr_3_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (f32(0.004000000));
				if (f32(0.140000000)) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(f32(0.140000000)), 0.000001)) * (1.0 - (f32(0.600000000))); else do envelope = (f32(0.600000000));
				voice.adsr_3_release_level = envelope;
				if time_in_decay >= (f32(0.140000000)) {
					voice.adsr_3_stage = .Sustain;
				}
			case .Sustain:
				envelope = (f32(0.600000000));
				voice.adsr_3_release_level = envelope;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (f32(0.220000000)) > 0 do envelope = voice.adsr_3_release_level * (1.0 - (time_in_release / math.max(f32(f32(0.220000000)), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_3_stage = .Idle;
				}
			}
			vel_scale_3: f32 = (1.0 - (f32(0.500000000))) + (f32(0.500000000)) * voice.velocity;
			node_3_out = ((node_1_out_gate + node_2_out)) * envelope * (f32(1.000000000)) * vel_scale_3;
		}

		output_left += node_3_out
		output_right += node_3_out
		if voice.adsr_3_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}
	if math.is_nan(output_left) || math.is_inf(output_left) || math.is_nan(output_right) || math.is_inf(output_right) {
		p.nonfinite_count += 1
		output_left, output_right = 0.0, 0.0
	}
	return skald_soft_limit(output_left * p.volume, output_right * p.volume)
}
Lead_process_sequence :: proc(p: ^Lead_Processor) {
}

Kick_2_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	noise_1_rng: PRNG_State,
	adsr_2_stage: ADSR_Stage,
	adsr_2_release_level: f32,
	adsr_2_attack_start: f32,
}

Kick_2_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [1]Kick_2_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	volume: f32,
	nonfinite_count: i32,
}

Kick_2_init :: proc(p: ^Kick_2_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 120.000000000
	p.volume = 0.800000012
	p.prng.state = 12345
	p.loop = true
	p.voices = {}
	p.total_samples = 0
	p.playing = false
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
	p.ext_in_l = 0.0
	p.ext_in_r = 0.0
	p.nonfinite_count = 0
	for i in 0..<1 {
		v := &p.voices[i]
		v.noise_1_rng.state = u32(0xC0FFEE01) ~ u32(i + 1) * 2654435761
	}
}

Kick_2_note_on :: proc(p: ^Kick_2_Processor, note: u8, velocity: f32, duration: f32) {
	// note and velocity are clamped silently to their MIDI/normalized domains.
	note := note
	if note > 127 do note = 127
	velocity := math.clamp(velocity, 0.0, 1.0)
	voice_idx := -1
	for i in 0..<1 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_releasing_age: f32 = -1.0
		for i in 0..<1 {
			releasing := true
			if p.voices[i].adsr_2_stage != .Release && p.voices[i].adsr_2_stage != .Idle do releasing = false
			if releasing && p.voices[i].age > oldest_releasing_age {
				oldest_releasing_age = p.voices[i].age
				voice_idx = i
			}
		}
		if voice_idx == -1 {
			oldest_age: f32 = -1.0
			for i in 0..<1 {
				if p.voices[i].age > oldest_age {
					oldest_age = p.voices[i].age
					voice_idx = i
				}
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	adsr_2_prev_level: f32 = 0.0
	if stolen && v.adsr_2_stage != .Idle {
		adsr_2_prev_level = v.adsr_2_release_level
		if v.adsr_2_stage == .Release {
			rel_t_2: f32 = (f32(0.030000000));
			if rel_t_2 > 0.0 {
				rf_2 := 1.0 - (v.age - v.time_released) / math.max(rel_t_2, 0.000001)
				if rf_2 < 0.0 do rf_2 = 0.0
				adsr_2_prev_level *= rf_2
			} else {
				adsr_2_prev_level = 0.0
			}
		}
	}
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.000000000
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.adsr_2_stage = .Attack
	v.adsr_2_attack_start = adsr_2_prev_level
	v.adsr_2_release_level = adsr_2_prev_level
}

Kick_2_note_off :: proc(p: ^Kick_2_Processor, note: u8) {
	// Clamped to match _note_on: `note` is the voice key, so both must map it.
	note := note
	if note > 127 do note = 127
	best := -1
	best_age: f32 = -1.0
	for i in 0..<1 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_2_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_2_stage = .Release
	}
}

Kick_2_trigger :: proc(p: ^Kick_2_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (f32(0.001000000)) + (f32(0.040000000)) > d do d = (f32(0.001000000)) + (f32(0.040000000))
		if d <= 0.0 do d = 0.001
	}
	Kick_2_note_on(p, note, velocity, d)
}

Kick_2_feed_input :: proc(p: ^Kick_2_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

Kick_2_start :: proc(p: ^Kick_2_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

Kick_2_stop :: proc(p: ^Kick_2_Processor) {
	p.playing = false
}

Kick_2_set_loop :: proc(p: ^Kick_2_Processor, loop: bool) {
	p.loop = loop
}

Kick_2_set_volume :: proc(p: ^Kick_2_Processor, value: f32) {
	p.volume = math.clamp(value, 0.0, 1.0)
}

Kick_2_is_playing :: proc(p: ^Kick_2_Processor) -> bool {
	if p.playing do return true
	for i in 0..<1 {
		if p.voices[i].active do return true
	}
	return false
}

Kick_2_PARAMS := []Skald_Param_Info{
}

Kick_2_set_param :: proc(p: ^Kick_2_Processor, name: string, value: f32) -> bool {
	return false
}

Kick_2_get_param :: proc(p: ^Kick_2_Processor, name: string) -> (f32, bool) {
	return 0.0, false
}

Kick_2_process :: proc(p: ^Kick_2_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	p.total_samples += 1

	for v_idx in 0..<1 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_2_stage != .Release && voice.adsr_2_stage != .Idle {
				voice.adsr_2_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_1_out: f32 = 0.0
		node_2_out: f32 = 0.0
		node_3_out: f32 = 0.0

		// --- Noise Node 1 ---
		node_1_out = (next_float32(&voice.noise_1_rng) * 2.0 - 1.0) * (f32(0.500000000));

		// --- ADSR Node 2 ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_2_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (f32(0.001000000)) > 0 do envelope = voice.adsr_2_attack_start + (1.0 - voice.adsr_2_attack_start) * (voice.age / math.max(f32(f32(0.001000000)), 0.000001)); else do envelope = 1.0;
				voice.adsr_2_release_level = envelope;
				if voice.age >= (f32(0.001000000)) {
					voice.adsr_2_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (f32(0.001000000));
				if (f32(0.040000000)) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(f32(0.040000000)), 0.000001)) * (1.0 - (f32(0.000000000))); else do envelope = (f32(0.000000000));
				voice.adsr_2_release_level = envelope;
				if time_in_decay >= (f32(0.040000000)) {
					voice.adsr_2_stage = .Sustain;
				}
			case .Sustain:
				envelope = (f32(0.000000000));
				voice.adsr_2_release_level = envelope;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (f32(0.030000000)) > 0 do envelope = voice.adsr_2_release_level * (1.0 - (time_in_release / math.max(f32(f32(0.030000000)), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_2_stage = .Idle;
				}
			}
			vel_scale_2: f32 = (1.0 - (f32(0.500000000))) + (f32(0.500000000)) * voice.velocity;
			node_2_out = ((node_1_out)) * envelope * (f32(1.000000000)) * vel_scale_2;
		}

		output_left += node_2_out
		output_right += node_2_out
		if voice.adsr_2_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}
	if math.is_nan(output_left) || math.is_inf(output_left) || math.is_nan(output_right) || math.is_inf(output_right) {
		p.nonfinite_count += 1
		output_left, output_right = 0.0, 0.0
	}
	return skald_soft_limit(output_left * p.volume, output_right * p.volume)
}
Kick_2_process_sequence :: proc(p: ^Kick_2_Processor) {
}

Bass_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	osc_1_phase: [1]f32,
	filter_2_low: f32,
	filter_2_band: f32,
	adsr_3_stage: ADSR_Stage,
	adsr_3_release_level: f32,
	adsr_3_attack_start: f32,
}

Bass_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [2]Bass_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	volume: f32,
	nonfinite_count: i32,
	cutoff: f32,
}

Bass_init :: proc(p: ^Bass_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 120.000000000
	p.volume = 0.850000024
	p.prng.state = 12345
	p.loop = true
	p.voices = {}
	p.total_samples = 0
	p.playing = false
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
	p.ext_in_l = 0.0
	p.ext_in_r = 0.0
	p.nonfinite_count = 0
	p.cutoff = 900.000000000
}

Bass_note_on :: proc(p: ^Bass_Processor, note: u8, velocity: f32, duration: f32) {
	// note and velocity are clamped silently to their MIDI/normalized domains.
	note := note
	if note > 127 do note = 127
	velocity := math.clamp(velocity, 0.0, 1.0)
	voice_idx := -1
	for i in 0..<2 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_releasing_age: f32 = -1.0
		for i in 0..<2 {
			releasing := true
			if p.voices[i].adsr_3_stage != .Release && p.voices[i].adsr_3_stage != .Idle do releasing = false
			if releasing && p.voices[i].age > oldest_releasing_age {
				oldest_releasing_age = p.voices[i].age
				voice_idx = i
			}
		}
		if voice_idx == -1 {
			oldest_age: f32 = -1.0
			for i in 0..<2 {
				if p.voices[i].age > oldest_age {
					oldest_age = p.voices[i].age
					voice_idx = i
				}
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	adsr_3_prev_level: f32 = 0.0
	if stolen && v.adsr_3_stage != .Idle {
		adsr_3_prev_level = v.adsr_3_release_level
		if v.adsr_3_stage == .Release {
			rel_t_3: f32 = (f32(0.200000000));
			if rel_t_3 > 0.0 {
				rf_3 := 1.0 - (v.age - v.time_released) / math.max(rel_t_3, 0.000001)
				if rf_3 < 0.0 do rf_3 = 0.0
				adsr_3_prev_level *= rf_3
			} else {
				adsr_3_prev_level = 0.0
			}
		}
	}
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.039999999
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.adsr_3_stage = .Attack
	v.adsr_3_attack_start = adsr_3_prev_level
	v.adsr_3_release_level = adsr_3_prev_level
	if !stolen {
		v.osc_1_phase = {}
		v.filter_2_low = 0.0
		v.filter_2_band = 0.0
	}
}

Bass_note_off :: proc(p: ^Bass_Processor, note: u8) {
	// Clamped to match _note_on: `note` is the voice key, so both must map it.
	note := note
	if note > 127 do note = 127
	best := -1
	best_age: f32 = -1.0
	for i in 0..<2 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_3_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_3_stage = .Release
	}
}

Bass_trigger :: proc(p: ^Bass_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (f32(0.010000000)) + (f32(0.200000000)) > d do d = (f32(0.010000000)) + (f32(0.200000000))
		if d <= 0.0 do d = 0.001
	}
	Bass_note_on(p, note, velocity, d)
}

Bass_feed_input :: proc(p: ^Bass_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

Bass_start :: proc(p: ^Bass_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

Bass_stop :: proc(p: ^Bass_Processor) {
	p.playing = false
}

Bass_set_loop :: proc(p: ^Bass_Processor, loop: bool) {
	p.loop = loop
}

Bass_set_volume :: proc(p: ^Bass_Processor, value: f32) {
	p.volume = math.clamp(value, 0.0, 1.0)
}

Bass_is_playing :: proc(p: ^Bass_Processor) -> bool {
	if p.playing do return true
	for i in 0..<2 {
		if p.voices[i].active do return true
	}
	return false
}

Bass_set_cutoff :: proc(p: ^Bass_Processor, value: f32) {
	v := value
	if v < 20.000000000 do v = 20.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.cutoff = v
}

Bass_PARAMS := []Skald_Param_Info{
	{"cutoff", 20.000000000, 20000.000000000, 900.000000000, "Hz"},
}

Bass_set_param :: proc(p: ^Bass_Processor, name: string, value: f32) -> bool {
	switch name {
	case "cutoff", "2::cutoff":
		Bass_set_cutoff(p, value)
		return true
	}
	return false
}

Bass_get_param :: proc(p: ^Bass_Processor, name: string) -> (f32, bool) {
	switch name {
	case "cutoff", "2::cutoff":
		return p.cutoff, true
	}
	return 0.0, false
}

Bass_process :: proc(p: ^Bass_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	p.total_samples += 1

	for v_idx in 0..<2 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.current_freq != voice.target_freq {
			glide_k := 1.0 / math.max(voice.glide_time * sample_rate, 1.0)
			if glide_k > 1.0 do glide_k = 1.0
			voice.current_freq += (voice.target_freq - voice.current_freq) * glide_k
			if abs(voice.target_freq - voice.current_freq) < 0.1 do voice.current_freq = voice.target_freq
		}
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_3_stage != .Release && voice.adsr_3_stage != .Idle {
				voice.adsr_3_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_1_out: f32 = 0.0
		node_2_out: f32 = 0.0
		node_3_out: f32 = 0.0
		node_4_out: f32 = 0.0

		// --- Oscillator Node 1 (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 1;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (0.000000000);
				detuned_freq: f32 = (voice.current_freq) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads: f32 = f32(f32(0.000000000)) * (f32(math.PI) / 180.0);
				voice.osc_1_phase[i] = math.mod(voice.osc_1_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := math.mod(voice.osc_1_phase[i] + phase_rads, 2 * f32(math.PI));
				unison_out += ((final_phase / f32(math.PI)) - 1.0);
			}
			node_1_out = (unison_out / f32(unison_count)) * (f32(0.600000000));
		}

		// --- Filter Node 2 (SVF) ---
		{
			cutoff_c_2: f32 = math.clamp(f32(p.cutoff), 10.0, sample_rate * 0.16);
			f_2 := f32(2.0 * math.sin(f32(math.PI) * cutoff_c_2 / sample_rate));
			q_2: f32 = math.clamp(1.0 / math.max(f32(f32(2.000000000)), 0.1), 0.05, 1.9 - f_2);
			voice.filter_2_low += f_2 * voice.filter_2_band;
			high_2 := f32(((node_1_out)) - voice.filter_2_low - q_2 * voice.filter_2_band);
			voice.filter_2_band += f_2 * high_2;
			node_2_out = voice.filter_2_low;
		}

		// --- ADSR Node 3 ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_3_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (f32(0.010000000)) > 0 do envelope = voice.adsr_3_attack_start + (1.0 - voice.adsr_3_attack_start) * (voice.age / math.max(f32(f32(0.010000000)), 0.000001)); else do envelope = 1.0;
				voice.adsr_3_release_level = envelope;
				if voice.age >= (f32(0.010000000)) {
					voice.adsr_3_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (f32(0.010000000));
				if (f32(0.200000000)) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(f32(0.200000000)), 0.000001)) * (1.0 - (f32(0.400000000))); else do envelope = (f32(0.400000000));
				voice.adsr_3_release_level = envelope;
				if time_in_decay >= (f32(0.200000000)) {
					voice.adsr_3_stage = .Sustain;
				}
			case .Sustain:
				envelope = (f32(0.400000000));
				voice.adsr_3_release_level = envelope;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (f32(0.200000000)) > 0 do envelope = voice.adsr_3_release_level * (1.0 - (time_in_release / math.max(f32(f32(0.200000000)), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_3_stage = .Idle;
				}
			}
			vel_scale_3: f32 = (1.0 - (f32(0.500000000))) + (f32(0.500000000)) * voice.velocity;
			node_3_out = ((node_2_out)) * envelope * (f32(1.000000000)) * vel_scale_3;
		}

		output_left += node_3_out
		output_right += node_3_out
		if voice.adsr_3_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}
	if math.is_nan(output_left) || math.is_inf(output_left) || math.is_nan(output_right) || math.is_inf(output_right) {
		p.nonfinite_count += 1
		output_left, output_right = 0.0, 0.0
	}
	return skald_soft_limit(output_left * p.volume, output_right * p.volume)
}
Bass_process_sequence :: proc(p: ^Bass_Processor) {
}

Kick_3_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	osc_2_phase: [1]f32,
	adsr_3_stage: ADSR_Stage,
	adsr_3_release_level: f32,
	adsr_3_attack_start: f32,
}

Kick_3_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [1]Kick_3_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	volume: f32,
	nonfinite_count: i32,
}

Kick_3_init :: proc(p: ^Kick_3_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 120.000000000
	p.volume = 0.949999988
	p.prng.state = 12345
	p.loop = true
	p.voices = {}
	p.total_samples = 0
	p.playing = false
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
	p.ext_in_l = 0.0
	p.ext_in_r = 0.0
	p.nonfinite_count = 0
}

Kick_3_note_on :: proc(p: ^Kick_3_Processor, note: u8, velocity: f32, duration: f32) {
	// note and velocity are clamped silently to their MIDI/normalized domains.
	note := note
	if note > 127 do note = 127
	velocity := math.clamp(velocity, 0.0, 1.0)
	voice_idx := -1
	for i in 0..<1 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_releasing_age: f32 = -1.0
		for i in 0..<1 {
			releasing := true
			if p.voices[i].adsr_3_stage != .Release && p.voices[i].adsr_3_stage != .Idle do releasing = false
			if releasing && p.voices[i].age > oldest_releasing_age {
				oldest_releasing_age = p.voices[i].age
				voice_idx = i
			}
		}
		if voice_idx == -1 {
			oldest_age: f32 = -1.0
			for i in 0..<1 {
				if p.voices[i].age > oldest_age {
					oldest_age = p.voices[i].age
					voice_idx = i
				}
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	adsr_3_prev_level: f32 = 0.0
	if stolen && v.adsr_3_stage != .Idle {
		adsr_3_prev_level = v.adsr_3_release_level
		if v.adsr_3_stage == .Release {
			rel_t_3: f32 = (f32(0.060000000));
			if rel_t_3 > 0.0 {
				rf_3 := 1.0 - (v.age - v.time_released) / math.max(rel_t_3, 0.000001)
				if rf_3 < 0.0 do rf_3 = 0.0
				adsr_3_prev_level *= rf_3
			} else {
				adsr_3_prev_level = 0.0
			}
		}
	}
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.000000000
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.adsr_3_stage = .Attack
	v.adsr_3_attack_start = adsr_3_prev_level
	v.adsr_3_release_level = adsr_3_prev_level
	if !stolen {
		v.osc_2_phase = {}
	}
}

Kick_3_note_off :: proc(p: ^Kick_3_Processor, note: u8) {
	// Clamped to match _note_on: `note` is the voice key, so both must map it.
	note := note
	if note > 127 do note = 127
	best := -1
	best_age: f32 = -1.0
	for i in 0..<1 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_3_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_3_stage = .Release
	}
}

Kick_3_trigger :: proc(p: ^Kick_3_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (f32(0.002000000)) + (f32(0.110000000)) > d do d = (f32(0.002000000)) + (f32(0.110000000))
		if d <= 0.0 do d = 0.001
	}
	Kick_3_note_on(p, note, velocity, d)
}

Kick_3_feed_input :: proc(p: ^Kick_3_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

Kick_3_start :: proc(p: ^Kick_3_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

Kick_3_stop :: proc(p: ^Kick_3_Processor) {
	p.playing = false
}

Kick_3_set_loop :: proc(p: ^Kick_3_Processor, loop: bool) {
	p.loop = loop
}

Kick_3_set_volume :: proc(p: ^Kick_3_Processor, value: f32) {
	p.volume = math.clamp(value, 0.0, 1.0)
}

Kick_3_is_playing :: proc(p: ^Kick_3_Processor) -> bool {
	if p.playing do return true
	for i in 0..<1 {
		if p.voices[i].active do return true
	}
	return false
}

Kick_3_PARAMS := []Skald_Param_Info{
}

Kick_3_set_param :: proc(p: ^Kick_3_Processor, name: string, value: f32) -> bool {
	return false
}

Kick_3_get_param :: proc(p: ^Kick_3_Processor, name: string) -> (f32, bool) {
	return 0.0, false
}

Kick_3_process :: proc(p: ^Kick_3_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	Kick_3_process_sequence(p)
	p.total_samples += 1

	for v_idx in 0..<1 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_3_stage != .Release && voice.adsr_3_stage != .Idle {
				voice.adsr_3_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_1_out: f32 = 0.0
		node_2_out: f32 = 0.0
		node_3_out: f32 = 0.0
		node_4_out: f32 = 0.0

		// --- MIDI Input Node 1 ---
		node_1_out_pitch := (f32(voice.note) - 69.0) / 12.0
		node_1_out_gate := f32(1.0)
		if voice.time_released > 0.0 do node_1_out_gate = 0.0
		node_1_out_velocity := voice.velocity

		// --- Oscillator Node 2 (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 1;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (0.000000000);
				detuned_freq: f32 = ((voice.current_freq) * math.pow(2.0, math.clamp(f32(node_1_out_pitch), -10.0, 10.0))) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads: f32 = f32(f32(0.000000000)) * (f32(math.PI) / 180.0);
				voice.osc_2_phase[i] = math.mod(voice.osc_2_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := math.mod(voice.osc_2_phase[i] + phase_rads, 2 * f32(math.PI));
				unison_out += (2.0 / f32(math.PI)) * math.asin(math.sin(final_phase));
			}
			node_2_out = (unison_out / f32(unison_count)) * (f32(0.700000000));
		}

		// --- ADSR Node 3 ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_3_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (f32(0.002000000)) > 0 do envelope = voice.adsr_3_attack_start + (1.0 - voice.adsr_3_attack_start) * (voice.age / math.max(f32(f32(0.002000000)), 0.000001)); else do envelope = 1.0;
				voice.adsr_3_release_level = envelope;
				if voice.age >= (f32(0.002000000)) {
					voice.adsr_3_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (f32(0.002000000));
				if (f32(0.110000000)) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(f32(0.110000000)), 0.000001)) * (1.0 - (f32(0.000000000))); else do envelope = (f32(0.000000000));
				voice.adsr_3_release_level = envelope;
				if time_in_decay >= (f32(0.110000000)) {
					voice.adsr_3_stage = .Sustain;
				}
			case .Sustain:
				envelope = (f32(0.000000000));
				voice.adsr_3_release_level = envelope;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (f32(0.060000000)) > 0 do envelope = voice.adsr_3_release_level * (1.0 - (time_in_release / math.max(f32(f32(0.060000000)), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_3_stage = .Idle;
				}
			}
			vel_scale_3: f32 = (1.0 - (f32(0.500000000))) + (f32(0.500000000)) * voice.velocity;
			node_3_out = ((node_1_out_gate + node_2_out)) * envelope * (f32(1.000000000)) * vel_scale_3;
		}

		output_left += node_3_out
		output_right += node_3_out
		if voice.adsr_3_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}
	if math.is_nan(output_left) || math.is_inf(output_left) || math.is_nan(output_right) || math.is_inf(output_right) {
		p.nonfinite_count += 1
		output_left, output_right = 0.0, 0.0
	}
	return skald_soft_limit(output_left * p.volume, output_right * p.volume)
}
Kick_3_process_sequence :: proc(p: ^Kick_3_Processor) {
	if !p.playing do return
	samples_per_step_f := p.sample_rate * 60.0 / (p.bpm * 4.0)
	if p.samples_until_next_step == 0 {
		// Track "Kick C" (16 steps)
		switch p.current_step % 16 {
		case 2:
			Kick_3_note_on(p, 36, 0.800000012, f32(0.100000001) * (60.0 / p.bpm / 4.0))
		case 10:
			Kick_3_note_on(p, 36, 0.800000012, f32(0.100000001) * (60.0 / p.bpm / 4.0))
		}
		p.current_step += 1
		if p.current_step >= 16 {
			if p.loop {
				p.current_step = 0
			} else {
				p.playing = false
			}
		}
		p.step_frac_acc += samples_per_step_f
		n_step := u64(math.max(p.step_frac_acc, 1.0))
		p.step_frac_acc -= f32(n_step)
		p.samples_until_next_step = n_step - 1
	} else {
		p.samples_until_next_step -= 1
	}
}

Lead_2_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	osc_2_phase: [1]f32,
	adsr_3_stage: ADSR_Stage,
	adsr_3_release_level: f32,
	adsr_3_attack_start: f32,
}

Lead_2_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [4]Lead_2_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	volume: f32,
	nonfinite_count: i32,
}

Lead_2_init :: proc(p: ^Lead_2_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 120.000000000
	p.volume = 0.699999988
	p.prng.state = 12345
	p.loop = true
	p.voices = {}
	p.total_samples = 0
	p.playing = false
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
	p.ext_in_l = 0.0
	p.ext_in_r = 0.0
	p.nonfinite_count = 0
}

Lead_2_note_on :: proc(p: ^Lead_2_Processor, note: u8, velocity: f32, duration: f32) {
	// note and velocity are clamped silently to their MIDI/normalized domains.
	note := note
	if note > 127 do note = 127
	velocity := math.clamp(velocity, 0.0, 1.0)
	voice_idx := -1
	for i in 0..<4 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_releasing_age: f32 = -1.0
		for i in 0..<4 {
			releasing := true
			if p.voices[i].adsr_3_stage != .Release && p.voices[i].adsr_3_stage != .Idle do releasing = false
			if releasing && p.voices[i].age > oldest_releasing_age {
				oldest_releasing_age = p.voices[i].age
				voice_idx = i
			}
		}
		if voice_idx == -1 {
			oldest_age: f32 = -1.0
			for i in 0..<4 {
				if p.voices[i].age > oldest_age {
					oldest_age = p.voices[i].age
					voice_idx = i
				}
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	adsr_3_prev_level: f32 = 0.0
	if stolen && v.adsr_3_stage != .Idle {
		adsr_3_prev_level = v.adsr_3_release_level
		if v.adsr_3_stage == .Release {
			rel_t_3: f32 = (f32(0.180000000));
			if rel_t_3 > 0.0 {
				rf_3 := 1.0 - (v.age - v.time_released) / math.max(rel_t_3, 0.000001)
				if rf_3 < 0.0 do rf_3 = 0.0
				adsr_3_prev_level *= rf_3
			} else {
				adsr_3_prev_level = 0.0
			}
		}
	}
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.020000000
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.adsr_3_stage = .Attack
	v.adsr_3_attack_start = adsr_3_prev_level
	v.adsr_3_release_level = adsr_3_prev_level
	if !stolen {
		v.osc_2_phase = {}
	}
}

Lead_2_note_off :: proc(p: ^Lead_2_Processor, note: u8) {
	// Clamped to match _note_on: `note` is the voice key, so both must map it.
	note := note
	if note > 127 do note = 127
	best := -1
	best_age: f32 = -1.0
	for i in 0..<4 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_3_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_3_stage = .Release
	}
}

Lead_2_trigger :: proc(p: ^Lead_2_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (f32(0.006000000)) + (f32(0.120000000)) > d do d = (f32(0.006000000)) + (f32(0.120000000))
		if d <= 0.0 do d = 0.001
	}
	Lead_2_note_on(p, note, velocity, d)
}

Lead_2_feed_input :: proc(p: ^Lead_2_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

Lead_2_start :: proc(p: ^Lead_2_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

Lead_2_stop :: proc(p: ^Lead_2_Processor) {
	p.playing = false
}

Lead_2_set_loop :: proc(p: ^Lead_2_Processor, loop: bool) {
	p.loop = loop
}

Lead_2_set_volume :: proc(p: ^Lead_2_Processor, value: f32) {
	p.volume = math.clamp(value, 0.0, 1.0)
}

Lead_2_is_playing :: proc(p: ^Lead_2_Processor) -> bool {
	if p.playing do return true
	for i in 0..<4 {
		if p.voices[i].active do return true
	}
	return false
}

Lead_2_PARAMS := []Skald_Param_Info{
}

Lead_2_set_param :: proc(p: ^Lead_2_Processor, name: string, value: f32) -> bool {
	return false
}

Lead_2_get_param :: proc(p: ^Lead_2_Processor, name: string) -> (f32, bool) {
	return 0.0, false
}

Lead_2_process :: proc(p: ^Lead_2_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	Lead_2_process_sequence(p)
	p.total_samples += 1

	for v_idx in 0..<4 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.current_freq != voice.target_freq {
			glide_k := 1.0 / math.max(voice.glide_time * sample_rate, 1.0)
			if glide_k > 1.0 do glide_k = 1.0
			voice.current_freq += (voice.target_freq - voice.current_freq) * glide_k
			if abs(voice.target_freq - voice.current_freq) < 0.1 do voice.current_freq = voice.target_freq
		}
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_3_stage != .Release && voice.adsr_3_stage != .Idle {
				voice.adsr_3_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_1_out: f32 = 0.0
		node_2_out: f32 = 0.0
		node_3_out: f32 = 0.0
		node_4_out: f32 = 0.0

		// --- MIDI Input Node 1 ---
		node_1_out_pitch := (f32(voice.note) - 69.0) / 12.0
		node_1_out_gate := f32(1.0)
		if voice.time_released > 0.0 do node_1_out_gate = 0.0
		node_1_out_velocity := voice.velocity

		// --- Oscillator Node 2 (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 1;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (0.000000000);
				detuned_freq: f32 = ((voice.current_freq) * math.pow(2.0, math.clamp(f32(node_1_out_pitch), -10.0, 10.0))) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads: f32 = f32(f32(0.000000000)) * (f32(math.PI) / 180.0);
				voice.osc_2_phase[i] = math.mod(voice.osc_2_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := math.mod(voice.osc_2_phase[i] + phase_rads, 2 * f32(math.PI));
				if final_phase < 2 * f32(math.PI) * math.clamp(f32(f32(0.500000000)), 0.01, 0.99) do unison_out += 1.0; else do unison_out -= 1.0;
			}
			node_2_out = (unison_out / f32(unison_count)) * (f32(0.400000000));
		}

		// --- ADSR Node 3 ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_3_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (f32(0.006000000)) > 0 do envelope = voice.adsr_3_attack_start + (1.0 - voice.adsr_3_attack_start) * (voice.age / math.max(f32(f32(0.006000000)), 0.000001)); else do envelope = 1.0;
				voice.adsr_3_release_level = envelope;
				if voice.age >= (f32(0.006000000)) {
					voice.adsr_3_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (f32(0.006000000));
				if (f32(0.120000000)) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(f32(0.120000000)), 0.000001)) * (1.0 - (f32(0.500000000))); else do envelope = (f32(0.500000000));
				voice.adsr_3_release_level = envelope;
				if time_in_decay >= (f32(0.120000000)) {
					voice.adsr_3_stage = .Sustain;
				}
			case .Sustain:
				envelope = (f32(0.500000000));
				voice.adsr_3_release_level = envelope;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (f32(0.180000000)) > 0 do envelope = voice.adsr_3_release_level * (1.0 - (time_in_release / math.max(f32(f32(0.180000000)), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_3_stage = .Idle;
				}
			}
			vel_scale_3: f32 = (1.0 - (f32(0.500000000))) + (f32(0.500000000)) * voice.velocity;
			node_3_out = ((node_1_out_gate + node_2_out)) * envelope * (f32(1.000000000)) * vel_scale_3;
		}

		output_left += node_3_out
		output_right += node_3_out
		if voice.adsr_3_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}
	if math.is_nan(output_left) || math.is_inf(output_left) || math.is_nan(output_right) || math.is_inf(output_right) {
		p.nonfinite_count += 1
		output_left, output_right = 0.0, 0.0
	}
	return skald_soft_limit(output_left * p.volume, output_right * p.volume)
}
Lead_2_process_sequence :: proc(p: ^Lead_2_Processor) {
	if !p.playing do return
	samples_per_step_f := p.sample_rate * 60.0 / (p.bpm * 4.0)
	if p.samples_until_next_step == 0 {
		// Track "Lead Z" (16 steps)
		switch p.current_step % 16 {
		case 1:
			Lead_2_note_on(p, 72, 0.899999976, f32(0.200000003) * (60.0 / p.bpm / 4.0))
		case 6:
			Lead_2_note_on(p, 76, 0.899999976, f32(0.200000003) * (60.0 / p.bpm / 4.0))
		case 11:
			Lead_2_note_on(p, 79, 0.899999976, f32(0.200000003) * (60.0 / p.bpm / 4.0))
		}
		p.current_step += 1
		if p.current_step >= 16 {
			if p.loop {
				p.current_step = 0
			} else {
				p.playing = false
			}
		}
		p.step_frac_acc += samples_per_step_f
		n_step := u64(math.max(p.step_frac_acc, 1.0))
		p.step_frac_acc -= f32(n_step)
		p.samples_until_next_step = n_step - 1
	} else {
		p.samples_until_next_step -= 1
	}
}

// --- Project Wrapper (test-harness convenience) ---
Project_State :: struct {
	Kick: ^Kick_Processor,
	Lead: ^Lead_Processor,
	Kick_2: ^Kick_2_Processor,
	Bass: ^Bass_Processor,
	Kick_3: ^Kick_3_Processor,
	Lead_2: ^Lead_2_Processor,
	master_volume: f32,
	dc: Skald_Dc_Block_State,
}

project_init :: proc(p: ^Project_State, sr: f32) {
	p.master_volume = 1.000000000
	p.dc = {}
	p.Kick = new(Kick_Processor)
	Kick_init(p.Kick, sr)
	Kick_start(p.Kick)
	p.Lead = new(Lead_Processor)
	Lead_init(p.Lead, sr)
	p.Kick_2 = new(Kick_2_Processor)
	Kick_2_init(p.Kick_2, sr)
	p.Bass = new(Bass_Processor)
	Bass_init(p.Bass, sr)
	p.Kick_3 = new(Kick_3_Processor)
	Kick_3_init(p.Kick_3, sr)
	Kick_3_start(p.Kick_3)
	p.Lead_2 = new(Lead_2_Processor)
	Lead_2_init(p.Lead_2, sr)
	Lead_2_start(p.Lead_2)
}

project_set_master_volume :: proc(p: ^Project_State, value: f32) {
	p.master_volume = math.clamp(value, 0.0, 1.0)
}

project_process :: proc(p: ^Project_State) -> (f32, f32) {
	mixed_left: f32 = 0.0
	mixed_right: f32 = 0.0
	{ l, r := Kick_process(p.Kick); mixed_left += l; mixed_right += r }
	{ l, r := Lead_process(p.Lead); mixed_left += l; mixed_right += r }
	{ l, r := Kick_2_process(p.Kick_2); mixed_left += l; mixed_right += r }
	{ l, r := Bass_process(p.Bass); mixed_left += l; mixed_right += r }
	{ l, r := Kick_3_process(p.Kick_3); mixed_left += l; mixed_right += r }
	{ l, r := Lead_2_process(p.Lead_2); mixed_left += l; mixed_right += r }
	mixed_left *= p.master_volume
	mixed_right *= p.master_volume
	mixed_left, mixed_right = skald_dc_block(&p.dc, mixed_left, mixed_right)
	return skald_soft_limit(mixed_left, mixed_right)
}

project_destroy :: proc(p: ^Project_State) {
	free(p.Kick)
	free(p.Lead)
	free(p.Kick_2)
	free(p.Bass)
	free(p.Kick_3)
	free(p.Lead_2)
}

